AttributeError when accessing PatientID when `Continued Progess` setting is enabled
[Issue]
When the continued progress setting is enabled and all DICOM files have been
processed, clicking on the "Load Next" button results in an AttributeError
on `self.logic.currentDicomDataset` because the Dicom dataset is not loaded.

```sh
SlicerUltrasound/AnonymizeUltrasound/AnonymizeUltrasound.py", line 529, in onNextButton
    patientID = self.logic.currentDicomDataset.PatientID
AttributeError: 'NoneType' object has no attribute 'PatientID'
```

[Solution]
Exit early and log status to user if `onNextButton` function is called but
all file have been processed and the `Continued Progress` setting is enabled.
Currently this use case results in `self.logic.nextDicomDfIndex` getting set to None.
A future refactor should consider looking into ways of storing this state to
avoid side effects.

[Test]
0. Load input and output folder with identical set of DICOM files.
1. Enable "Continued Progress"
2. Click "Import DICOM folder"
3. Click "Load next"

You should see a status indicating all DICOM files have been processed.